// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultipleContexts.Models.Contexts;

#nullable disable

namespace MultipleContexts.Migrations.Customers
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultipleContexts.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f9283b9-89ba-4c3e-8765-955c07c83a53"),
                            CreatedDate = new DateTime(2024, 1, 4, 18, 33, 1, 580, DateTimeKind.Utc).AddTicks(6296),
                            Name = "Customer One",
                            Surname = "Surname One"
                        },
                        new
                        {
                            Id = new Guid("ad26f214-9cd9-4f0f-a1b1-37f886701607"),
                            CreatedDate = new DateTime(2024, 1, 4, 18, 33, 1, 580, DateTimeKind.Utc).AddTicks(6521),
                            Name = "Customer Two",
                            Surname = "Surname Two"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
