// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultipleContexts.Models.Contexts;

#nullable disable

namespace MultipleContexts.Migrations.Products
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20240104183225_AddProductEntity")]
    partial class AddProductEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultipleContexts.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("390dd7eb-023a-40c9-9c34-b7afd16e827e"),
                            CreatedDate = new DateTime(2024, 1, 4, 18, 32, 25, 160, DateTimeKind.Utc).AddTicks(8089),
                            Name = "Product One",
                            Price = 111L,
                            Stock = 1
                        },
                        new
                        {
                            Id = new Guid("2545c8ba-656d-48c5-b5e3-30427281efb0"),
                            CreatedDate = new DateTime(2024, 1, 4, 18, 32, 25, 160, DateTimeKind.Utc).AddTicks(8301),
                            Name = "Product Two",
                            Price = 222L,
                            Stock = 2
                        },
                        new
                        {
                            Id = new Guid("0b39e809-6389-4d6e-9f2e-99513ea9d9d5"),
                            CreatedDate = new DateTime(2024, 1, 4, 18, 32, 25, 160, DateTimeKind.Utc).AddTicks(8303),
                            Name = "Product Three",
                            Price = 333L,
                            Stock = 3
                        },
                        new
                        {
                            Id = new Guid("cb5bd7f2-7bb3-4a96-bcbb-9c7839cc9474"),
                            CreatedDate = new DateTime(2024, 1, 4, 18, 32, 25, 160, DateTimeKind.Utc).AddTicks(8304),
                            Name = "Product Four",
                            Price = 444L,
                            Stock = 4
                        },
                        new
                        {
                            Id = new Guid("ec95a3c5-aba3-4470-9363-a95a238dd3ce"),
                            CreatedDate = new DateTime(2024, 1, 4, 18, 32, 25, 160, DateTimeKind.Utc).AddTicks(8315),
                            Name = "Product Five",
                            Price = 555L,
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("5029e9cf-163f-4f03-a321-d306d4e022f5"),
                            CreatedDate = new DateTime(2024, 1, 4, 18, 32, 25, 160, DateTimeKind.Utc).AddTicks(8317),
                            Name = "Product Six",
                            Price = 666L,
                            Stock = 6
                        },
                        new
                        {
                            Id = new Guid("0119866c-433c-47aa-8e56-eb18e7f3e03d"),
                            CreatedDate = new DateTime(2024, 1, 4, 18, 32, 25, 160, DateTimeKind.Utc).AddTicks(8318),
                            Name = "Product Seven",
                            Price = 777L,
                            Stock = 7
                        },
                        new
                        {
                            Id = new Guid("3c44d022-fea7-465e-b230-3a2d7de0da79"),
                            CreatedDate = new DateTime(2024, 1, 4, 18, 32, 25, 160, DateTimeKind.Utc).AddTicks(8320),
                            Name = "Product Eight",
                            Price = 888L,
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("c2717dc7-0fee-47d6-aefe-14614f1a54cf"),
                            CreatedDate = new DateTime(2024, 1, 4, 18, 32, 25, 160, DateTimeKind.Utc).AddTicks(8322),
                            Name = "Product Nine",
                            Price = 999L,
                            Stock = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
